# .github/workflows/kev-sync.yml
name: Sync KEV data

on:
  # every hour
  schedule:
    - cron: "0 12-23 * * *" # every hour 12:00-23:00 UTC (~7am-6pm or 8am-7pmET depending on DST)
  workflow_dispatch: {}

permissions:
  contents: write

jobs:
  sync:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 1

      - name: Fetch to temp and stage only if content changed
        shell: bash
        run: |
          set -euo pipefail
          CSV_URL="https://www.cisa.gov/sites/default/files/csv/known_exploited_vulnerabilities.csv"
          JSON_URL="https://www.cisa.gov/sites/default/files/feeds/known_exploited_vulnerabilities.json"

          CSV="known_exploited_vulnerabilities.csv"
          JSON="known_exploited_vulnerabilities.json"

          # Download fresh to temp files
          curl -fSLo "${CSV}.tmp"  "$CSV_URL"
          curl -fSLo "${JSON}.tmp" "$JSON_URL"

          changed_files=""

          # If file missing or bytes differ -> replace and mark changed
          if [ ! -f "$CSV" ] || ! cmp -s "${CSV}.tmp" "$CSV"; then
            mv -f "${CSV}.tmp" "$CSV"
            changed_files="$changed_files $CSV"
            echo "CSV changed → will commit."
          else
            rm -f "${CSV}.tmp"
            echo "CSV unchanged."
          fi

          if [ ! -f "$JSON" ] || ! cmp -s "${JSON}.tmp" "$JSON"; then
            mv -f "${JSON}.tmp" "$JSON"
            changed_files="$changed_files $JSON"
            echo "JSON changed → will commit."
          else
            rm -f "${JSON}.tmp"
            echo "JSON unchanged."
          fi

          # Save list for next step
          echo "$changed_files" > .changed_files

      - name: Commit only changed files
        shell: bash
        run: |
          set -euo pipefail
          changed_files="$(tr -s ' ' < .changed_files || true)"
          if [ -n "$changed_files" ]; then
            git config user.name  "kev-sync-bot"
            git config user.email "actions@users.noreply.github.com"
            git add $changed_files
            echo "Staging:$changed_files"
            git commit -m "chore: sync KEV data $(date -u +'%Y-%m-%dT%H:%M:%SZ')"
            git push
            echo "Changes committed & pushed."
          else
            echo "No content changes."
          fi
